### PR TITLE
Added Force, Recursive, Zero Blocks

### PR DESCRIPTION
**Pull request by TroyWilson1**

### CODE REVIEW

**Comment by tdlm** [comment]
@TroyWilson1 Why the recursive flag for files?

**Comment by TroyWilson1** [comment]
I must of done a global replace. Sorry about that, I'm still figuring out how this works.

**Comment by tdlm** [comment]
@TroyWilson1 No problem. The Zero blocks flag looks promising. I haven't seen that before. Do you know what the ultimate difference is in using it?

**Comment by TroyWilson1** [comment]
The zero blocks flag writes zeros over the blocks that the deleted file/s occopied so that even if the hard drive is savaged. It helps block against software/block recovery software that authorities use to pull deleted files from drives. 

This zero block flag helps best with older drives with platters. Newer SSD hard drives are not really aided by this flag but ultimately fall under true erasing/secure removal via TRIM support. This alone is a whole other conversation. 

I hope it helps. I’m still figuring out git works so I’m sorry for any problems. 

-- 
Troy Wilson

On April 17, 2015 at 3:05:29 PM, Scott Weaver (notifications@github.com) wrote:

@TroyWilson1 No problem. The Zero blocks flag looks promising. I haven't seen that before. Do you know what the ultimate difference is in using it?

**Comment by tdlm** [comment]
@TroyWilson1 Good info though. Thanks!

I'd say just make another commit after you remove the recursive flag in the appropriate areas. I wouldn't want a mistake in that way. :)

**Comment by tdlm** [comment]
Thanks @TroyWilson1

**Pull request merged**
